import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/TopMenu";
import Sidebar, { SidebarItem } from "@/components/Sidebar";
import { BarChart3, LayoutDashboard, LifeBuoy, Settings, UserCircle } from "lucide-react";
import SessionProviderWrapper from "@/components/SessionProviderWrapper ";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProviderWrapper> 
        <div className="flex h-screen w-full">
          
          <Sidebar>
            <SidebarItem icon={<LayoutDashboard size={20} />} text="Home" pageRef = '/'/>
            <SidebarItem icon={<BarChart3 size={20} />} text="Review"  pageRef = '/review'/>
            <SidebarItem icon={<UserCircle size={20} />} text="Users" pageRef = '/user' />
            <hr className="my-3" />
            <SidebarItem icon={<Settings size={20} />} text="Settings" pageRef = '/setting' />
            <SidebarItem icon={<LifeBuoy size={20} />} text="Help" pageRef = '/help' />
          </Sidebar>

          <main className="flex bg-gray-100 overflow-auto">
            {children}
          </main>
        </div>
        </SessionProviderWrapper> 
      </body>
    </html>
  );
}
